version: "2"
services:
  podcasts-server:
    build: .
    restart: unless-stopped
    networks:
      webserver:
        aliases:
          - podcasts-server
    expose:
      - "80"

networks:
  webserver:
      external: true
